name: Pre-commit
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-extensions:
    runs-on: [self-hosted, linux]
    container: node:16.14.2-buster
    env:
      NODE_OPTIONS: "--max-old-space-size=4096"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build the package
        run: yarn install  && yarn package
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: launcher-extension
          path: ./*.vsix
